openapi: 3.0.0
info:
  title: Crawler Benefits API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /benefits/detailed:
    post:
      summary: Retorna o número de benefício de um aposentado ou pensionista
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                cpf:
                  type: string
                  description: CPF do aposentado ou pensionista
                login_user:
                  type: string
                  description: Usuário para fazer login no portal
                login_password:
                  type: string
                  description: Senha para fazer login no portal
              required:
                - cpf
                - login_user
                - login_password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  numero_beneficio:
                    type: string
                    description: Número do benefício do aposentado ou pensionista
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Erro
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Erro
