version: '3'
services:
    app:
        build: .
        container_name: crawler_app_upload
        volumes:
            - ".:/root/app"
            - "app_upload:/root/app/upload"
        ports:
            - "3000:3000"
        restart: always

        
volumes:
    app_upload: